---
# Notes:
# Sample project C code is not presently written to produce a release artifact.
# As such, release build options are disabled.
# This sample, therefore, only demonstrates running a collection of unit tests.

:project:
  :use_exceptions: FALSE
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :build_root: build
  #  :release_build: TRUE
  :test_file_prefix: tdd_
  :which_ceedling: gem
  :ceedling_version: 0.31.1
  :default_tasks:
    - test:all

#:test_build:
#  :use_assembly: TRUE

#:release_build:
#  :output: MyApp.out
#  :use_assembly: FALSE

:environment:

:extension:
  :executable: .out

:paths:
  :test:
    - +:test/**
    - -:test/support
  :source:
    - src/Master/SRC/modem/nbiot_lg/nbiotResponse.c
    - src/Master/SRC/dev/flashDriver.c
    - src/Master/SRC/app/meter.c
    - src/Master/SRC/app/rtcAlarm.c
    - src/Master/SRC/app/nfcProtocol.c
  :support:
    - test/support
  :libraries: []
  :include:
    - src/Master/SRC/modem/nbiot_lg/**
    - src/Master/SRC/app/**
    - src/Master/SRC/dev/**
    - src/Master/SRC/test/**
    - src/Master/SRC/misc/**
    - src/Master/SRC/osal/**

:defines:
  # in order to add common defines:
  #  1) remove the trailing [] from the :common: section
  #  2) add entries to the :common: section (e.g. :test: has TEST defined)
  :common: &common_defines
    - TDD_TEST
    - NBIOT_MODEM_BC95G
    - NBIOT_LG_TYPE
    - NBIOT_DEVICE
  :test:
    - *common_defines
    - TEST
    - TDD_DEBUG
  :test_preprocess:
    - *common_defines
    - TEST

:cmock:
  :mock_prefix: mock_
  :when_no_prototypes: :warn
  :enforce_strict_ordering: TRUE
  :plugins:
    - :ignore
    - :callback
  :treat_as:
    uint8: HEX8
    uint16: HEX16
    uint32: UINT32
    int8: INT8
    bool: UINT8

:plugins:
  :enabled:
    # - stdout_gtestlike_tests_report
    - stdout_pretty_tests_report
    - warnings_report
    - raw_output_report
    - module_generator
    - warnings_report
    - raw_output_report
    - gcov

:gcov:
  :reports:
    - HtmlDetailed
:html_report_type: detailed
:gcovr:
  :html_absolute_paths: false
  :print_summary: true

# :tools:
#   :gcov_report:
#     :executable: gcov
#     :arguments:
#       - -p
#       - -b
#       - -o "$": GCOV_BUILD_OUTPUT_PATH
#       - '"${1}"'
#   :gcov_post_report:
#     # :executable: gcovr
#     :executable: lcov
#     # :optional: FALSE
#     :arguments:
#       - -p
#       - -b
#       - -k
#       - -e '.*tools.*|.*build.*|.*test/Test.*'
#       - --html
#       - --html-details
#       - -r .
#       - -o build/artifacts/gcov/index.html

# :tools:
#   :test_compiler:
#     :executable: gcc-11
# :arguments:
#   - "-std=c99"
---
# Add -gcov to the plugins list to make sure of the gcov plugin
# You will need to have gcov and gcovr both installed to make it work.
# For more information on these options, see docs in plugins/gcov

#:tools:
# Ceedling defaults to using gcc for compiling, linking, etc.
# As [:tools] is blank, gcc will be used (so long as it's in your system path)
# See documentation to configure a given toolchain for use

# LIBRARIES
# These libraries are automatically injected into the build process. Those specified as
# common will be used in all types of builds. Otherwise, libraries can be injected in just
# tests or releases. These options are MERGED with the options in supplemental yaml files.
:libraries:
  :placement: :end
  :flag: "-l${1}"
  :path_flag: "-L ${1}"
  :system: [] # for example, you might list 'm' to grab the math library
  :test: []
  :release: []

:plugins:
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
